version: '3'
networks:
  my-app-network: null

services:
  java:
    buidl: .
    context: Dockerfile
    container_name: JAVA_BACKEND
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BE_PORT=${BE_PORT}
      - DB_PORT=${DB_PORT}
    networks:
      - my-app-network
    depends_on:
      - my-database-for-java-app
    
  my-database-for-java-app:
    image: mysql:8.0
    container_name: '${DB_HOST}'
    networks:
      - my-app-network
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD={DB_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DB_PORT}:3306'